# Generated by Django 4.2.3 on 2023-07-05 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_product_promo_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='eidted',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='upload',
            field=models.DateField(auto_now=True),
        ),
    ]
