# Generated by Django 4.2.3 on 2023-07-06 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_catimh_category_catimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='eidted',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='upload',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
