# Generated by Django 4.2.3 on 2023-07-10 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_eidted_product_edited_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Category',
            new_name='category',
        ),
    ]
