# Generated by Django 4.2.3 on 2023-07-12 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_contact_screenshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='screenshot',
            field=models.ImageField(blank=True, default='img/emma.jpg', null=True, upload_to='screenshot'),
        ),
    ]
