# Generated by Django 4.2.3 on 2023-07-23 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_privacypolicy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrivacyPolicy',
        ),
    ]
